version: "3.7"

services:
  php:
    image: graphicresources/itpg-api-coding-task:development
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www
    networks:
      - bridge

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge

networks:
  bridge:

volumes:
  db-data:
