version: "3.7"

services:
  php:
    image: ghcr.io/ralonsogit/lotr-api:latest
    working_dir: /var/www
    command: sh -c "php artisan migrate --database=lotr --seed && php artisan migrate --database=testing_db && php -S 0.0.0.0:8080 -t public"
    environment:
      docker: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www
    networks:
      - bridge
    depends_on:
      - db
      - redis

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./opt/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotr
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - bridge

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bridge

networks:
  bridge:

volumes:
  db-data:
  redis-data:
