name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to ghcr.io
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_PAT }}

      # Step 3: Build & push docker image
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/ralonsogit/lotr-api:latest
          docker push ghcr.io/ralonsogit/lotr-api:latest
